### ISSUE TITLE
ffpython doesn't execute entire.py file

### ISSUE THREAD

**Issue by ionab10** [tomchen/font-template#1]
On Windows 10, running `ffpython batch_import_svg.py` exits after for loop on line 15.

When i run it line by line in ffpython shell, it exports to `output.sfd` but that file is 1KB and is empty when open in FontForge.

**Comment by tomchen** [comment]
Hi, Sounds like you have successfully executed the whole `batch_import_svg.py` script including the last line `font.save('output.sfd')`, and generated `output.sfd`. But, `output.sfd` contained no glyphs.

Make sure you have a folder named "SVG" in the same folder of `batch_import_svg.py` ([screenshot 4](https://github.com/tomchen/font-template/blob/master/img/4-fontforge_import.png)). "SVG" folder contains **individual glyph SVG files** named as `65 A.svg`, `66 B.svg`, etc. These .svg files should have been exported with Adobe Illustrator during the last step ([screenshot 3](https://github.com/tomchen/font-template/blob/master/img/3-ai_export.png)).

You could move `font-template/example/SVG/` folder up one level (to `font-template/SVG/`) then try it using the example instead of your own .svg files if you don't have any.

**Comment by ionab10** [comment]
Hi, thanks for the response. For some reason, running `ffpython batch-import-svg.py` doesn't execute fully so I manually executed each line (line-by-line) in the ffpython shell. This created the sfd but which contained no glyphs. 

The SVG path is /font-template/SVG and contains my .svg files and the python script is /font-template/batch-import-svg.py. Perhaps there is something wrong with the SVG files that were exported from Adobe Illustrator because when I try to import them individually to FontForge, FontForge crashes.

Also, the example directory is gitignored. If you could provide your example then I'll try with that and see if it's just a my SVGs that are bad. Thanks.

**Comment by tomchen** [comment]
Oh I totally forgot `/example/` had been gitignored. It's now tracked. You can `cd` to `/font-template/example/`, rename or delete `output.sfd` file, then try `ffpython batch-import-svg.py` in that directory, see if it generates a 12KB `output.sfd` file.

**Comment by tomchen** [comment]
Btw my `ffpython --version` is Python 3.7.4 (note that `pathlib` that I use requires Python > 3.4).

`fontforge --version` is [...] Version: 20190801 [...].

Illustrator's version is 23.0.3

**Comment by tomchen** [comment]
I can confirm that FontForge Windows Version 20200314 crashes when importing SVG files, while Windows Version 20190801, Linux Versions 20200314 and 20190801 all work fine.

Both GUI and command line/script have problem importing SVG files, for example, this file: https://github.com/tomchen/font-template/blob/master/example/SVG/48%200.svg.

It is reported by other user via email that some SVG files can be imported while some cannot.

I'm reporting the issue here: fontforge/fontforge/issues/4396

For now, Windows user should uninstall FontForge Versions 20200314 and install Version 20190801:
https://github.com/fontforge/fontforge/releases/download/20190801/FontForge-2019-08-01-Windows.exe

**Comment by tomchen** [comment]
Added this:

> (**ATTENTION: FontForge Windows Version 20200314 crashes when importing SVG files. This has been fixed but a newer FontForge stable version hasn't been released yet. For now, Windows user should use either a recent non-release build ([2020-06-30 build](https://ci.appveyor.com/api/buildjobs/5tceko609vdf4stw/artifacts/fontforgebuilds%2FFontForge-mingw-w64-i686-81b621-appveyor.7z)), or Version 20190801 release ([download](https://github.com/fontforge/fontforge/releases/download/20190801/FontForge-2019-08-01-Windows.exe)).** FontForge Linux versions do not have this bug)

It is actually recommended user use a recent non-release build instead of 20190801 stable release (see https://github.com/fontforge/fontforge/issues/4396#issuecomment-652534683)
